-- Catálogo público de Wicel.
-- Generado desde /api/catalogo. No contiene usuarios, pedidos, sesiones ni credenciales.
-- Importar después de database/wicel.sql.
SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO brands (name, slug, is_active) VALUES ('Apple', 'apple', 1) ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO brands (name, slug, is_active) VALUES ('Genérico', 'generico', 1) ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO brands (name, slug, is_active) VALUES ('Metamate', 'metamate', 1) ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO brands (name, slug, is_active) VALUES ('Stanley', 'stanley', 1) ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO brands (name, slug, is_active) VALUES ('Watersy', 'watersy', 1) ON DUPLICATE KEY UPDATE is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Azul', '#2563eb', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Blanco', '#f4f4f5', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Celeste', '#7cc4f0', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Crema', '#efe6d2', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Crema con mapa', '#efe8d6', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Crema con moños', '#f3e3c4', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Lila', '#d8b4fe', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Lima y fucsia', '#c9e27a', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Naranja', '#e8732a', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Natural', '#e8dcc4', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Negro', '#1c1c1e', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Plateado', '#c0c4cc', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Rojo', '#c8102e', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Rosa', '#f4b6c2', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Verde', '#1f8a4c', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Verde lima', '#b5c934', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Verde oliva', '#7d8b5a', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;
INSERT INTO colors (name, hex_code, is_active) VALUES ('Violeta', '#8b7cf6', 1) ON DUPLICATE KEY UPDATE hex_code = VALUES(hex_code), is_active = 1;

-- El respaldo representa exactamente los productos activos del catálogo.
UPDATE products SET is_active = 0 WHERE product_type <> 'COMBO';

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (31, (SELECT id FROM brands WHERE name = 'Apple'), 1, 'iPhone 15 128GB', 'iphone-15-128gb-2', 'Pantalla Super Retina XDR de 6,1 pulgadas\nCámara principal de 48 MP\nDynamic Island\nEquipo nuevo, disponibilidad por encargo', 'ASK_PRICE', 'PHONE', 0, 1, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 31;
DELETE FROM product_images WHERE product_id = 31;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (33, 31, 'WI-CATALOG-33', (SELECT id FROM colors WHERE name = 'Negro'), (SELECT id FROM storage_options WHERE label = '128 GB'), 6, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 33, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (31, 33, '/catalogo/productos/p31-v33.webp', 'iPhone 15 128GB Negro', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (34, 31, 'WI-CATALOG-34', (SELECT id FROM colors WHERE name = 'Azul'), (SELECT id FROM storage_options WHERE label = '128 GB'), 6, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 34, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (31, 34, '/catalogo/productos/p31-v34.webp', 'iPhone 15 128GB Azul', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (35, 31, 'WI-CATALOG-35', (SELECT id FROM colors WHERE name = 'Rosa'), (SELECT id FROM storage_options WHERE label = '128 GB'), 6, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 35, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (31, 35, '/catalogo/productos/p31-v35.webp', 'iPhone 15 128GB Rosa', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (32, (SELECT id FROM brands WHERE name = 'Apple'), 1, 'iPhone 16 128GB', 'iphone-16-128gb', 'Pantalla Super Retina XDR de 6,1 pulgadas\nControl de la Cámara\nChip A18\nEquipo nuevo, disponibilidad por encargo', 'ASK_PRICE', 'PHONE', 0, 1, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 32;
DELETE FROM product_images WHERE product_id = 32;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (36, 32, 'WI-CATALOG-36', (SELECT id FROM colors WHERE name = 'Negro'), (SELECT id FROM storage_options WHERE label = '128 GB'), 8, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 36, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (32, 36, '/catalogo/productos/p32-v36.webp', 'iPhone 16 128GB Negro', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (37, 32, 'WI-CATALOG-37', (SELECT id FROM colors WHERE name = 'Blanco'), (SELECT id FROM storage_options WHERE label = '128 GB'), 8, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 37, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (32, 37, '/catalogo/productos/p32-v37.webp', 'iPhone 16 128GB Blanco', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (38, 32, 'WI-CATALOG-38', (SELECT id FROM colors WHERE name = 'Rosa'), (SELECT id FROM storage_options WHERE label = '128 GB'), 8, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 38, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (32, 38, '/catalogo/productos/p32-v38.webp', 'iPhone 16 128GB Rosa', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (33, (SELECT id FROM brands WHERE name = 'Apple'), 1, 'iPhone 17 256GB', 'iphone-17-256gb', 'Pantalla Super Retina XDR\nCámara principal de 48 MP\nEquipo nuevo, disponibilidad por encargo', 'ASK_PRICE', 'PHONE', 0, 1, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 33;
DELETE FROM product_images WHERE product_id = 33;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (39, 33, 'WI-CATALOG-39', (SELECT id FROM colors WHERE name = 'Negro'), (SELECT id FROM storage_options WHERE label = '256 GB'), 8, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 39, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (33, 39, '/catalogo/productos/p33-v39.webp', 'iPhone 17 256GB Negro', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (40, 33, 'WI-CATALOG-40', (SELECT id FROM colors WHERE name = 'Blanco'), (SELECT id FROM storage_options WHERE label = '256 GB'), 8, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 40, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (33, 40, '/catalogo/productos/p33-v40.webp', 'iPhone 17 256GB Blanco', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (41, 33, 'WI-CATALOG-41', (SELECT id FROM colors WHERE name = 'Lila'), (SELECT id FROM storage_options WHERE label = '256 GB'), 8, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 41, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (33, 41, '/catalogo/productos/p33-v41.webp', 'iPhone 17 256GB Lila', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (34, (SELECT id FROM brands WHERE name = 'Apple'), 1, 'iPhone 17 Pro 256GB', 'iphone-17-pro-256gb', 'Modelo Pro con pantalla Super Retina XDR\nSistema de cámaras Pro\nEquipo nuevo, disponibilidad por encargo', 'ASK_PRICE', 'PHONE', 0, 1, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 34;
DELETE FROM product_images WHERE product_id = 34;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (42, 34, 'WI-CATALOG-42', (SELECT id FROM colors WHERE name = 'Plateado'), (SELECT id FROM storage_options WHERE label = '256 GB'), 12, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 42, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (34, 42, '/catalogo/productos/p34-v42.webp', 'iPhone 17 Pro 256GB Plateado', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (43, 34, 'WI-CATALOG-43', (SELECT id FROM colors WHERE name = 'Azul'), (SELECT id FROM storage_options WHERE label = '256 GB'), 12, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 43, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (34, 43, '/catalogo/productos/p34-v43.webp', 'iPhone 17 Pro 256GB Azul', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (44, 34, 'WI-CATALOG-44', (SELECT id FROM colors WHERE name = 'Naranja'), (SELECT id FROM storage_options WHERE label = '256 GB'), 12, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 44, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (34, 44, '/catalogo/productos/p34-v44.webp', 'iPhone 17 Pro 256GB Naranja', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (35, (SELECT id FROM brands WHERE name = 'Apple'), 1, 'iPhone 17 Pro Max 256GB', 'iphone-17-pro-max-256gb', 'Modelo Pro Max con pantalla Super Retina XDR\nSistema de cámaras Pro\nEquipo nuevo, disponibilidad por encargo', 'ASK_PRICE', 'PHONE', 0, 1, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 35;
DELETE FROM product_images WHERE product_id = 35;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (45, 35, 'WI-CATALOG-45', (SELECT id FROM colors WHERE name = 'Plateado'), (SELECT id FROM storage_options WHERE label = '256 GB'), 12, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 45, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (35, 45, '/catalogo/productos/p35-v45.webp', 'iPhone 17 Pro Max 256GB Plateado', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (46, 35, 'WI-CATALOG-46', (SELECT id FROM colors WHERE name = 'Azul'), (SELECT id FROM storage_options WHERE label = '256 GB'), 12, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 46, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (35, 46, '/catalogo/productos/p35-v46.webp', 'iPhone 17 Pro Max 256GB Azul', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (47, 35, 'WI-CATALOG-47', (SELECT id FROM colors WHERE name = 'Naranja'), (SELECT id FROM storage_options WHERE label = '256 GB'), 12, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 47, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (35, 47, '/catalogo/productos/p35-v47.webp', 'iPhone 17 Pro Max 256GB Naranja', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (36, (SELECT id FROM brands WHERE name = 'Apple'), 1, 'iPhone 18 Pro 256GB', 'iphone-18-pro-256gb', 'Modelo Pro con pantalla Super Retina XDR\nSistema de cámaras Pro\nEquipo nuevo, disponibilidad por encargo', 'ASK_PRICE', 'PHONE', 0, 1, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 36;
DELETE FROM product_images WHERE product_id = 36;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (48, 36, 'WI-CATALOG-48', (SELECT id FROM colors WHERE name = 'Negro'), (SELECT id FROM storage_options WHERE label = '256 GB'), 12, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 48, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (36, 48, '/catalogo/productos/p36-v48.webp', 'iPhone 18 Pro 256GB Negro', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (49, 36, 'WI-CATALOG-49', (SELECT id FROM colors WHERE name = 'Plateado'), (SELECT id FROM storage_options WHERE label = '256 GB'), 12, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 49, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (36, 49, '/catalogo/productos/p36-v49.webp', 'iPhone 18 Pro 256GB Plateado', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (50, 36, 'WI-CATALOG-50', (SELECT id FROM colors WHERE name = 'Celeste'), (SELECT id FROM storage_options WHERE label = '256 GB'), 12, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 50, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (36, 50, '/catalogo/productos/p36-v50.webp', 'iPhone 18 Pro 256GB Celeste', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (37, (SELECT id FROM brands WHERE name = 'Apple'), 1, 'iPhone 18 Pro Max 256GB', 'iphone-18-pro-max-256gb', 'Modelo Pro Max con pantalla Super Retina XDR\nSistema de cámaras Pro\nEquipo nuevo, disponibilidad por encargo', 'ASK_PRICE', 'PHONE', 0, 1, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 37;
DELETE FROM product_images WHERE product_id = 37;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (51, 37, 'WI-CATALOG-51', (SELECT id FROM colors WHERE name = 'Negro'), (SELECT id FROM storage_options WHERE label = '256 GB'), 12, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 51, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (37, 51, '/catalogo/productos/p37-v51.webp', 'iPhone 18 Pro Max 256GB Negro', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (52, 37, 'WI-CATALOG-52', (SELECT id FROM colors WHERE name = 'Plateado'), (SELECT id FROM storage_options WHERE label = '256 GB'), 12, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 52, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (37, 52, '/catalogo/productos/p37-v52.webp', 'iPhone 18 Pro Max 256GB Plateado', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (53, 37, 'WI-CATALOG-53', (SELECT id FROM colors WHERE name = 'Celeste'), (SELECT id FROM storage_options WHERE label = '256 GB'), 12, 'NEW', 0, NULL, 1, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 53, 0, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (37, 53, '/catalogo/productos/p37-v53.webp', 'iPhone 18 Pro Max 256GB Celeste', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (41, (SELECT id FROM brands WHERE name = 'Stanley'), 3, 'Botella térmica Stanley con tapa vaso', 'botella-termica-stanley-con-tapa-vaso', 'Acero inoxidable con doble pared\nTapa que se usa como vaso', NULL, 'OTHER', 0, 0, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 41;
DELETE FROM product_images WHERE product_id = 41;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (67, 41, 'WI-CATALOG-67', (SELECT id FROM colors WHERE name = 'Rojo'), NULL, NULL, 'NEW', 59000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 67, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (41, 67, '/catalogo/productos/p41-v67.jpg', 'Botella térmica Stanley con tapa vaso Rojo', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (68, 41, 'WI-CATALOG-68', (SELECT id FROM colors WHERE name = 'Rosa'), NULL, NULL, 'NEW', 59000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 68, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (41, 68, '/catalogo/productos/p41-v68.jpg', 'Botella térmica Stanley con tapa vaso Rosa', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (45, (SELECT id FROM brands WHERE name = 'Watersy'), 3, 'Botella térmica Watersy', 'botella-termica-watersy', 'Botella térmica de acero inoxidable\nTapa a rosca', 'ASK_PRICE', 'OTHER', 0, 0, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 45;
DELETE FROM product_images WHERE product_id = 45;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (75, 45, 'WI-CATALOG-75', (SELECT id FROM colors WHERE name = 'Celeste'), NULL, NULL, 'NEW', 0, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 75, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (45, 75, '/catalogo/productos/p45-v75.jpg', 'Botella térmica Watersy Celeste', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (44, (SELECT id FROM brands WHERE name = 'Metamate'), 3, 'Mate autocebante Metamate XL 600 ml', 'mate-autocebante-metamate-xl-600-ml', 'Capacidad 600 ml\nMate autocebante con bombilla', 'ASK_PRICE', 'OTHER', 0, 0, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 44;
DELETE FROM product_images WHERE product_id = 44;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (73, 44, 'WI-CATALOG-73', (SELECT id FROM colors WHERE name = 'Verde'), NULL, NULL, 'NEW', 0, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 73, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (44, 73, '/catalogo/productos/p44-v73.jpg', 'Mate autocebante Metamate XL 600 ml Verde', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (74, 44, 'WI-CATALOG-74', (SELECT id FROM colors WHERE name = 'Lila'), NULL, NULL, 'NEW', 0, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 74, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (44, 74, '/catalogo/productos/p44-v74.jpg', 'Mate autocebante Metamate XL 600 ml Lila', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (40, (SELECT id FROM brands WHERE name = 'Stanley'), 3, 'Stanley Quencher H2.0 1,2 L', 'stanley-quencher-h2-0-1-2-l', 'Capacidad 1,2 litros\nAcero inoxidable con doble pared\nManija y tapa con sorbete', NULL, 'OTHER', 0, 0, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 40;
DELETE FROM product_images WHERE product_id = 40;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (58, 40, 'WI-CATALOG-58', (SELECT id FROM colors WHERE name = 'Rojo'), NULL, NULL, 'NEW', 59000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 58, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (40, 58, '/catalogo/productos/p40-v58.jpg', 'Stanley Quencher H2.0 1,2 L Rojo', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (59, 40, 'WI-CATALOG-59', (SELECT id FROM colors WHERE name = 'Crema'), NULL, NULL, 'NEW', 59000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 59, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (40, 59, '/catalogo/productos/p40-v59.jpg', 'Stanley Quencher H2.0 1,2 L Crema', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (60, 40, 'WI-CATALOG-60', (SELECT id FROM colors WHERE name = 'Negro'), NULL, NULL, 'NEW', 59000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 60, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (40, 60, '/catalogo/productos/p40-v60.jpg', 'Stanley Quencher H2.0 1,2 L Negro', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (61, 40, 'WI-CATALOG-61', (SELECT id FROM colors WHERE name = 'Azul'), NULL, NULL, 'NEW', 59000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 61, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (40, 61, '/catalogo/productos/p40-v61.jpg', 'Stanley Quencher H2.0 1,2 L Azul', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (62, 40, 'WI-CATALOG-62', (SELECT id FROM colors WHERE name = 'Celeste'), NULL, NULL, 'NEW', 59000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 62, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (40, 62, '/catalogo/productos/p40-v62.jpg', 'Stanley Quencher H2.0 1,2 L Celeste', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (63, 40, 'WI-CATALOG-63', (SELECT id FROM colors WHERE name = 'Verde lima'), NULL, NULL, 'NEW', 59000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 63, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (40, 63, '/catalogo/productos/p40-v63.jpg', 'Stanley Quencher H2.0 1,2 L Verde lima', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (64, 40, 'WI-CATALOG-64', (SELECT id FROM colors WHERE name = 'Lima y fucsia'), NULL, NULL, 'NEW', 59000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 64, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (40, 64, '/catalogo/productos/p40-v64.jpg', 'Stanley Quencher H2.0 1,2 L Lima y fucsia', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (65, 40, 'WI-CATALOG-65', (SELECT id FROM colors WHERE name = 'Verde oliva'), NULL, NULL, 'NEW', 59000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 65, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (40, 65, '/catalogo/productos/p40-v65.jpg', 'Stanley Quencher H2.0 1,2 L Verde oliva', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (66, 40, 'WI-CATALOG-66', (SELECT id FROM colors WHERE name = 'Rosa'), NULL, NULL, 'NEW', 59000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 66, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (40, 66, '/catalogo/productos/p40-v66.jpg', 'Stanley Quencher H2.0 1,2 L Rosa', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (42, (SELECT id FROM brands WHERE name = 'Genérico'), 3, 'Vaso térmico 620 ml', 'vaso-termico-620-ml', 'Capacidad 620 ml\nTapa con sorbete y correa COFFEE\nDiseños: moños o mapa de viaje', NULL, 'OTHER', 0, 0, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 42;
DELETE FROM product_images WHERE product_id = 42;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (69, 42, 'WI-CATALOG-69', (SELECT id FROM colors WHERE name = 'Crema con moños'), NULL, NULL, 'NEW', 38000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 69, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (42, 69, '/catalogo/productos/p42-v69.jpg', 'Vaso térmico 620 ml Crema con moños', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (70, 42, 'WI-CATALOG-70', (SELECT id FROM colors WHERE name = 'Crema con mapa'), NULL, NULL, 'NEW', 38000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 70, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (42, 70, '/catalogo/productos/p42-v70.jpg', 'Vaso térmico 620 ml Crema con mapa', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (43, (SELECT id FROM brands WHERE name = 'Genérico'), 3, 'Vaso térmico COFFEE 500 ml', 'vaso-termico-coffee-500-ml', 'Capacidad 500 ml\nTapa con cierre y correa COFFEE', NULL, 'OTHER', 0, 0, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 43;
DELETE FROM product_images WHERE product_id = 43;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (71, 43, 'WI-CATALOG-71', (SELECT id FROM colors WHERE name = 'Natural'), NULL, NULL, 'NEW', 26000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 71, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (43, 71, '/catalogo/productos/p43-v71.jpg', 'Vaso térmico COFFEE 500 ml Natural', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (72, 43, 'WI-CATALOG-72', (SELECT id FROM colors WHERE name = 'Azul'), NULL, NULL, 'NEW', 26000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 72, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (43, 72, '/catalogo/productos/p43-v72.jpg', 'Vaso térmico COFFEE 500 ml Azul', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (38, (SELECT id FROM brands WHERE name = 'Genérico'), 3, 'Vaso térmico con brillo 900 ml', 'vaso-termico-con-brillo-900-ml', 'Capacidad 900 ml\nTerminación con brillo\nTapa con sorbete', NULL, 'OTHER', 0, 0, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 38;
DELETE FROM product_images WHERE product_id = 38;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (54, 38, 'WI-CATALOG-54', (SELECT id FROM colors WHERE name = 'Lila'), NULL, NULL, 'NEW', 38000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 54, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (38, 54, '/catalogo/productos/p38-v54.jpg', 'Vaso térmico con brillo 900 ml Lila', 0, 1);

INSERT INTO products (id, brand_id, category_id, name, slug, description, short_description, product_type, warranty_months, is_featured, is_active) VALUES (39, (SELECT id FROM brands WHERE name = 'Genérico'), 3, 'Vaso térmico con strass 1,2 L', 'vaso-termico-con-strass-1-2-l', 'Capacidad 1,2 litros\nRevestimiento de strass\nManija y tapa con sorbete', NULL, 'OTHER', 0, 0, 1) ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id), name = VALUES(name), slug = VALUES(slug), description = VALUES(description), short_description = VALUES(short_description), product_type = VALUES(product_type), is_featured = VALUES(is_featured), is_active = 1;
UPDATE product_variants SET is_active = 0 WHERE product_id = 39;
DELETE FROM product_images WHERE product_id = 39;
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (55, 39, 'WI-CATALOG-55', (SELECT id FROM colors WHERE name = 'Azul'), NULL, NULL, 'NEW', 48000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 55, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (39, 55, '/catalogo/productos/p39-v55.jpg', 'Vaso térmico con strass 1,2 L Azul', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (56, 39, 'WI-CATALOG-56', (SELECT id FROM colors WHERE name = 'Violeta'), NULL, NULL, 'NEW', 48000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 56, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (39, 56, '/catalogo/productos/p39-v56.jpg', 'Vaso térmico con strass 1,2 L Violeta', 0, 1);
INSERT INTO product_variants (id, product_id, sku, color_id, storage_id, ram_gb, condition_type, sale_price, compare_at_price, weight_grams, is_active) VALUES (57, 39, 'WI-CATALOG-57', (SELECT id FROM colors WHERE name = 'Verde'), NULL, NULL, 'NEW', 48000, NULL, NULL, 1) ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), color_id = VALUES(color_id), storage_id = VALUES(storage_id), ram_gb = VALUES(ram_gb), condition_type = VALUES(condition_type), sale_price = VALUES(sale_price), compare_at_price = VALUES(compare_at_price), weight_grams = VALUES(weight_grams), is_active = 1;
INSERT INTO inventory_stock (warehouse_id, variant_id, quantity, minimum_stock) VALUES ((SELECT id FROM warehouses WHERE is_active = 1 ORDER BY id LIMIT 1), 57, 1, 5) ON DUPLICATE KEY UPDATE quantity = VALUES(quantity), minimum_stock = VALUES(minimum_stock);
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, position, is_primary) VALUES (39, 57, '/catalogo/productos/p39-v57.jpg', 'Vaso térmico con strass 1,2 L Verde', 0, 1);

COMMIT;
